name: emotic_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24
  - scipy
  - scikit-learn
  - matplotlib
  - opencv
  - pytorch
  - torchvision
  - tensorboardx
  - pip
  - pip:
      - tqdm